### ISSUE TITLE
CXSparse test

### ISSUE THREAD

**Issue by matzeri** [sfabbro/suitesparse#2]
Matrix directory needed for "Make check"

--- addons/CXSparse/Makefile.am~        2012-11-21 15:44:40.000000000 +0100
+++ addons/CXSparse/Makefile.am 2013-01-07 21:50:17.555034700 +0100
@@ -5,6 +5,6 @@

 SUBDIRS = Source Demo Doc

-EXTRA_DIST += MATLAB
+EXTRA_DIST += MATLAB Matrix

 include_HEADERS = Include/cs.h

**Comment by sfabbro** [comment]
applied. thanks.
